### ISSUE TITLE
How to pass in API_KEY for QDrant cloud?

### ISSUE THREAD

**Issue by yusefmosiah** [marinac-dev/qdrant#3]
Hey, I really want to use this library for my app, but I don’t want to deploy QDrant myself right away. How does one use this library with QDrant’s managed cloud which requires an API key?

**Comment by marinac-dev** [comment]
Hi there, currently there isn't an option for that, so thank you for pointing it out! 
I recognize that this should be a core feature, and I will create a PR now and work on it ASAP.

**Comment by marinac-dev** [comment]
Resolved with [PR#4](https://github.com/marinac-dev/qdrant/pull/4)

**Comment by yusefmosiah** [comment]
awesome, thanks!
