### ISSUE TITLE
Points.delete_points/4 uses method: delete but it needs to use method: post

### ISSUE THREAD

**Issue by yusefmosiah** [marinac-dev/qdrant#8]
I made a PR to fix it.

Thanks again for making this awesome library, and appologies if I made any mistakes. This marks my first open source contribution haha.

**Comment by marinac-dev** [comment]
Hi @yusefmosiah 
Indeed, [Qdrant API docs ](https://qdrant.github.io/qdrant/redoc/index.html#tag/points/operation/delete_points) states to use POST request to delete points, good catch!

I am glad, welcome to Open Source community! 😃
